[package]
name = "rss_reader"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.98"
html2md = "0.2.15"
regex = "1.11.1"
reqwest = "0.12.19"
rss = "2.0.12"
soup = "0.5.1"
tokio = { version = "1.45.1", features = ["rt-multi-thread", "macros"] }
